// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/llmons/gin-template/internal/base/conf"
	"github.com/llmons/gin-template/internal/base/data"
	"github.com/llmons/gin-template/internal/base/server"
)

// Injectors from wire.go:

func initApplication(debug bool, dbConf *data.Database, serverConf *conf.Server) (*gin.Engine, func(), error) {
	engine := server.NewHTTPServer(debug)
	return engine, func() {
	}, nil
}
